### PR TITLE
fixed image and ebm page link with main page

### PR DESCRIPTION
**Pull request by sisminnmaw**
change bg image color
repair some img
ebm page link with main index

### CODE REVIEW

**Review by dreamingblackcat — CHANGES_REQUESTED** [review]
I found a few potential issues.
- Some image files are named with capitalized  extensions which will break images when hosted on case-sensitive file systems.
- When editing the cycle of mentor/participants/volunteers image, can we use primary yellow color as main color for the fills and secondary blue as txt and arrow color.

**Comment by sisminnmaw** [comment]
image

local image file extensions are lowercase, but it's not changing to git's file names.

**Comment by khinezarthwe** [comment]
Screen Shot 2022-12-20 at 22 02 07



Would like to add /update the following to that page.

- [x]  menu for 2023 program in headline 
- [x]  change email to hello@thingaha.org

**Comment by khinezarthwe** [comment]
Screen Shot 2022-12-20 at 22 05 17


- [x] can't see the image file of "Get started with Education-based Mertorship Program"
- [x] replace BETTER FUTURE FUNDRAISER WORKSHOPS with "Mental support and guidance for youths in Myanmar"
- [x] Remove >> "All our regular donation processes xxxx." and  replace with "Myanmar is currently in political turmoil and many students are at a lost. We aim to help them connect with a mentor who can help them achieve their educational goals."
- [x] add accessible button to view that program.

**Comment by khinezarthwe** [comment]
Screen Shot 2022-12-20 at 22 12 54

- [x] Please update the mission statement 
- [x] would like to put "2023 pilot program" in first slot.

**Comment by khinezarthwe** [comment]
- [x] wanna add Thandar , Sis Minn Maw and Hnin Oo Wai Hlaing in "About us"

**Comment by sisminnmaw** [comment]
left-
need to edit text and photos in the about us session. (Thandar, Moe Thae, Sis Minn Maw)

**Review by dreamingblackcat — APPROVED** [review]
LGTM

**Pull request merged**
